### ISSUE TITLE
Getting errors when trying to install

### ISSUE THREAD

**Issue by grennilson** [Eworm/Anchorman#18]
The command "php composer.phar update wout-mager/anchorman --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 1(General error)

Output:
================

Error Output:
================
Loading composer repositories with package information

                                                       
  [ErrorException]                                     
  Trying to access array offset on value of type null  
                                                       

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by Eworm** [comment]
The correct way to install addons for v2 is `php please update:addons`. Can you try that to see if that works?

**Comment by grennilson** [comment]
Yep… I did that…

[getclients@host public_html]$ php please update:addons
Adding packages: wout-mager/anchorman
Please wait while dependencies are updated via Composer. This may take a while.
The command "php composer.phar update wout-mager/anchorman --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 1(General error)

Output:
================


Error Output:
================
Loading composer repositories with package information

                                                       
  [ErrorException]                                     
  Trying to access array offset on value of type null  
                                                       

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...


Dependencies updated!

Could that have something to do with my php version?

Gary

**Comment by grennilson** [comment]
Now I have a bigger issue. Your add-on removed my option to save as draft and replaced it with an English/German toggle. I tried removing your Add-in but my site is still messed up!

**Comment by Eworm** [comment]
This doesn't sound like something my add-on could do but a problem somewhere else in your setup. It sounds like installing the addon worked?

**Comment by grennilson** [comment]
Very frustrating!!! I have been trying for 3 days to get your addon installed. I thought maybe it was conflicting with another addon but I just created a "fresh" copy of statamic 2 and just tried adding you addon. It keeps giving me a fatal error. I have over 2gm of memory_level added in my php.ini file... do you have a newer version of your code that works?


dev@Develops-iMac getclients % php please update:addons
Adding packages: wout-mager/anchorman
Please wait while dependencies are updated via Composer. This may take a while.
The command "php composer.phar update wout-mager/anchorman --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 255(Unknown error)

Output:
================

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///Users/dev/Sites/getclients/statamic/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

Error Output:
================
Loading composer repositories with package information
Updating dependencies

Dependencies updated!

**Comment by grennilson** [comment]
I'm using statamic version 2.11.20... that last update for version 2.0. Could this be the problem?

**Comment by grennilson** [comment]
so now I changed up the php.ini to unlimited memory -1 and am getting this error when trying to install...

[getclients@host dev]$ for i in $(scl -l);do echo $i;grep memory_limit /opt/cpanel/$i/root/etc/php.ini;echo;done
ea-php54
memory_limit = 128M

ea-php55
memory_limit = 128M

ea-php56
memory_limit = 128M

ea-php70
memory_limit = 128M

ea-php71
memory_limit = 2048M

ea-php74
memory_limit = -1 

[getclients@host dev]$ php please update:addons
Adding packages: wout-mager/anchorman
Please wait while dependencies are updated via Composer. This may take a while.

                                                          
  [Symfony\Component\Process\Exception\RuntimeException]  
  The process has been signaled with signal "9".          
                                                          

[getclients@host dev]$ 

...so what is going on with your addon? I haven't had any problems adding other peoples addons... I really would like to use the functionality of importing an rss feed and propagating it to a collection.

Is there another way to install your addon without using php please update:addons?

**Comment by Eworm** [comment]
I'm on version 2.11.20 on my test site for this addon. Just deleted it and did an update:addons with no problems. The problem with this is that the addon is still secretly installed. I also can't install a fresh v2 statamic to try a fresh install.

What happens if you add the addon, and then copy all addon files in statamic/vendor/wout-mager/anchorman? And add `"wout-mager/anchorman": "*@dev"` to composer.json in the statamic directory?

![Schermafbeelding 2020-09-17 om 19 33 18](https://user-images.githubusercontent.com/511488/93506555-bc31c400-f91c-11ea-8734-df2af5e92d07.png)

**Comment by Eworm** [comment]
[willvincent.zip](https://github.com/Eworm/Anchorman/files/5240945/willvincent.zip)
[simplepie.zip](https://github.com/Eworm/Anchorman/files/5240947/simplepie.zip)

These are zipped dirs of the dependencies. You should add these to statamic/vendor.

**Comment by grennilson** [comment]
I thought a quick loom video might help. I added the files and made sure that the code was in composer.json... still not working. https://www.loom.com/share/723bf318b3024b749daea939bcfb92c1

**Comment by grennilson** [comment]
Finally got it working after reinstalling composer.
